#%RAML 1.0
---

title: Mobile Tax Credits Summary
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/mobile-tax-credits-summary:
  /income:
    /{nino}:
      uriParameters:
        nino:
          description: The NINO for the individual.
          type: string
          example: NS123456B
      /tax-credits:
        /tax-credits-summary:
          get:
            displayName: Get tax credits summary
            description: This endpoint retrieves the tax credits summary.
            is: [headers.acceptHeader]
            (annotations.scope): "read:mobile-tax-credits-summary"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:mobile-tax-credits-summary" ] } ]
            queryParameters:
              journeyId:
                type: string
                required: false
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/get-tax-credits-summary-full-summary-example.json
                      example-2:
                        value: !include examples/get-tax-credits-summary-no-claimants-example.json
                      example-3:
                        value: !include examples/get-tax-credits-summary-excluded-user-example.json
                      example-4:
                        value: !include examples/get-tax-credits-summary-non-tax-credits-user-example.json
